#!/usr/bin/env python3
#! python3
# archwiki - Busca el programa / servicio en la wiki de arch
import webbrowser, requests, sys, bs4 

# Descarga la página con los resultados de la busqueda
url_to_open = 'https://wiki.archlinux.org/title/' + '+'.join(sys.argv[1:])

webbrowser.open(url_to_open)

