#!/usr/bin/env python3
import webbrowser, requests, sys, bs4

# res = requests.get('https://askubuntu.com/search?q=' + '+'.join(sys.argv[1:]))
# res.raise_for_status()

# soup = bs4.BeautifulSoup(res.text, 'html.parser')
# link_elems = soup.select('.question-hyperlink')

# num_open = min(3, len(link_elems))
# for i in range(num_open):
    # url_to_open = 'https://askubuntu.com' + link_elems[i].get('href')
    # print('Abriendo', url_to_open)
    # webbrowser.open(url_to_open)

if len(sys.argv) == 1:
    # Abrir pagina de busqueda de askubuntu si no se especifica nada
    address = 'https://askubuntu.com/search'
elif len(sys.argv) > 1:
    # Buscar en askubuntu lo escrito en la consola
    address = 'https://askubuntu.com/search?q=' + '+'.join(sys.argv[1:])

else:
    # Indicar que ha habido un error
    address = ''
    print('Se ha ingresado uno o más carácteres inválidos. Favor reintentar')
    sys.exit()


webbrowser.open(address)
