#!/usr/bin/env bash
#! python3
import webbrowser, sys, pyperclip

if len(sys.argv) > 1:
    # Leer la dirección desde la linea de comandos
    direccion = ' '.join(sys.argv[1:])
else:
    # Leer la dirección desde el portapapeles
    direccion = pyperclip.paste()

webbrowser.open('https://www.google.com/maps/place/' + direccion)
