#!/usr/bin/env python3
#!
#! python3
# mapIt.py - Lanza un mapa en el navegador usando
# una dirección indicada en la linea de comandos
# ó que esté en el portapapeles

import webbrowser, sys, pyperclip

if len(sys.argv) > 1:
    # Leer la dirección desde la linea de comandos
    direccion = ' '.join(sys.argv[1:])
else:
    # Leer la dirección desde el portapapeles
    direccion = pyperclip.paste()

webbrowser.open('https://www.google.com/maps/place/' + direccion)
    
