#!/usr/bin/env python3
import webbrowser, sys

if len (sys.argv) == 1:
    address = 'https://google.com'

elif str(sys.argv[1]).startswith('http'):
    address = ''.join(sys.argv[1:])

elif not str(sys.argv[1]).startswith('http') and str(sys.argv[1]).endswith(('.com','.cl','.net')):
    address = 'https://' + ''.join(sys.argv[1:])

else:
    address = 'https://google.com/search?q=' + '+'.join(sys.argv[1:])

try:
    webbrowser.open(address)
except:
    print('Hubo un problema con la dirección ingresada.')
